# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"3\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"4\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"@\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x12\n\x10ListUsersRequest\"(\n\x0cUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\".\n\x11ListUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\"#\n\x12SearchUsersRequest\x12\r\n\x05query\x18\x01 \x01(\t\"0\n\x13SearchUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User2\xf5\x02\n\x0bUserService\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12\x33\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\x12\x39\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12\x39\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x12.user.UserResponse\x12<\n\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x12\x42\n\x0bSearchUsers\x12\x18.user.SearchUsersRequest\x1a\x19.user.SearchUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=71
  _globals['_CREATEUSERREQUEST']._serialized_start=73
  _globals['_CREATEUSERREQUEST']._serialized_end=125
  _globals['_GETUSERREQUEST']._serialized_start=127
  _globals['_GETUSERREQUEST']._serialized_end=155
  _globals['_UPDATEUSERREQUEST']._serialized_start=157
  _globals['_UPDATEUSERREQUEST']._serialized_end=221
  _globals['_DELETEUSERREQUEST']._serialized_start=223
  _globals['_DELETEUSERREQUEST']._serialized_end=254
  _globals['_LISTUSERSREQUEST']._serialized_start=256
  _globals['_LISTUSERSREQUEST']._serialized_end=274
  _globals['_USERRESPONSE']._serialized_start=276
  _globals['_USERRESPONSE']._serialized_end=316
  _globals['_LISTUSERSRESPONSE']._serialized_start=318
  _globals['_LISTUSERSRESPONSE']._serialized_end=364
  _globals['_SEARCHUSERSREQUEST']._serialized_start=366
  _globals['_SEARCHUSERSREQUEST']._serialized_end=401
  _globals['_SEARCHUSERSRESPONSE']._serialized_start=403
  _globals['_SEARCHUSERSRESPONSE']._serialized_end=451
  _globals['_USERSERVICE']._serialized_start=454
  _globals['_USERSERVICE']._serialized_end=827
# @@protoc_insertion_point(module_scope)
